#!/usr/bin/env python3

# Avoid servers hosted in states that are party to a certain Western
# intelligence gathering alliance.

# pylint: disable=invalid-name
# pylint: disable=missing-function-docstring
# pylint: disable=missing-module-docstring

import itertools
import os
import shlex
import sys

from libexample import rm_fr

ichain = itertools.chain.from_iterable


PROG = "./mlvd-sample"

argv = [
    PROG, "-v",
    *ichain(["--reject-country", r] for r in ["au", "ca", "gb", "nz", "us"]),
    "src", "dst"]

print(" ".join(shlex.quote(a) for a in argv), file=sys.stderr)

rm_fr("dst")
sys.stderr.flush()
os.execv(PROG, argv)
